[package]
name = "cached-demo"
version = "0.1.0"
authors = ["zhangalex"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cache = "0.2.0"
